### ISSUE TITLE
MVPリリース_レビュー依頼

### ISSUE THREAD

**Issue by erijawa** [erijawa/oyasai_up#103]
MVP リリース用の issue を作成いたしました。
レビューのほどどうぞよろしくお願いいたします。

## 各種情報
サービス名：おやさいUP
サービスURL：https://oyasaiup-09896b03803b.herokuapp.com
Github：https://github.com/erijawa/oyasai_up

サービスの概要とMVPで検証する事柄：
忙しい生活の中で不足しがちな野菜の摂取を促進するためのアプリです。
毎日自分が野菜を食べたかを記録する機能と、野菜を食べた際のレポートを投稿し共有する機能があり、楽しみながら栄養バランスの向上をサポートします。
MVPでは大きく分けて下記の2機能を実装しています。

**野菜の食べ方のアイデア投稿「おやさいReport」**
野菜を食べた際のレポートを投稿できます。自炊したものだけではなく、コンビニやスーパーなどで購入したものでも投稿可能です。

**野菜を食べたかどうかの記録「おやさいlog」**
ユーザー登録をすると、毎日3食それぞれで野菜を食べたか記録できます。記録に応じてカレンダーが色づき、自分がどのくらい野菜を食べられているか一目で履歴をみることができます。

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x]  ユーザー登録機能
- [x]  ログイン機能
- [x]  新規投稿機能
- [x]  投稿一覧機能（未ログインでも閲覧可能）
- [x]  投稿詳細閲覧機能（未ログインでも閲覧可能）
- [x]  投稿編集機能
- [x]  投稿削除機能
- [x]  マイページ
- [ ] プロフィール編集機能
- [x]  野菜摂取カレンダーの表示
- [x]  自分の投稿一覧
- [x]  野菜摂取記録機能

## READMEレビュー時から変更した機能
- プロフィール編集機能：本リリース時に実装予定に変更しました

### ユーザー関係
|ログイン機能|新規登録機能|
|----|----|
|[![Image from Gyazo](https://i.gyazo.com/4370c14fa651f7ee2f20d2491032a908.jpg)](https://gyazo.com/4370c14fa651f7ee2f20d2491032a908)|[![Image from Gyazo](https://i.gyazo.com/f35960bdd17a27784709dd3f83da1728.jpg)](https://gyazo.com/f35960bdd17a27784709dd3f83da1728)|

### おやさいReport
|投稿一覧|投稿詳細|
|----|----|
|[![Image from Gyazo](https://i.gyazo.com/ae44d5f044f82a29022901f4556e493a.jpg)](https://gyazo.com/ae44d5f044f82a29022901f4556e493a)|[![Image from Gyazo](https://i.gyazo.com/c3fe452c159b49ede80816b941aef001.jpg)](https://gyazo.com/c3fe452c159b49ede80816b941aef001)|

|新規投稿作成|投稿編集機能|
|----|----|
|[![Image from Gyazo](https://i.gyazo.com/37d84a89bb3ce5a009ac434e401955d9.jpg)](https://gyazo.com/37d84a89bb3ce5a009ac434e401955d9)|[![Image from Gyazo](https://i.gyazo.com/95010a0cd8278798aec4f9222662d757.jpg)](https://gyazo.com/95010a0cd8278798aec4f9222662d757)|

|投稿削除機能|
|----|
|[![Image from Gyazo](https://i.gyazo.com/2359e26bafbbb7ce188c69890427cf7c.jpg)](https://gyazo.com/2359e26bafbbb7ce188c69890427cf7c)|

### おやさいLog(マイページ)
|おやさいLog閲覧|おやさいLog記録機能|
|----|----|
|[![Image from Gyazo](https://i.gyazo.com/e1df96f8a54d01e10fd56a2015a43933.jpg)](https://gyazo.com/e1df96f8a54d01e10fd56a2015a43933)|[![Image from Gyazo](https://i.gyazo.com/83d64a89f929f3df9d0aa61199ebddb1.jpg)](https://gyazo.com/83d64a89f929f3df9d0aa61199ebddb1)|

|自分の投稿一覧|
|----|
|[![Image from Gyazo](https://i.gyazo.com/0abc23c5793a998ca3c91c8773b88d0a.jpg)](https://gyazo.com/0abc23c5793a998ca3c91c8773b88d0a)|

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by erijawa** [comment]
ご確認いただきありがとうございます！
引き続きよろしくお願いいたします。
