### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by erijawa** [erijawa/oyasai_up#41]
MVPリリースまでの実装予定内容です。
ご確認をお願いいたします。

■Webアプリの概要

忙しい生活の中で不足しがちな野菜の摂取を促進するためのアプリです。
毎日自分が野菜を食べたかを記録する機能と、野菜を食べた際のレポートを投稿し共有する機能があり、楽しみながら栄養バランスの向上をサポートします。

**野菜を食べたかどうかの記録「おやさいlog」**
ユーザー登録をすると、毎日3食それぞれで野菜を食べたかどうか記録できます。その日に「野菜を食べた」と記録した回数に応じてカレンダーが色づき、自分がどのくらいの頻度で野菜を食べられているか一目で履歴をみることができます。

**野菜の食べ方のアイデア投稿「おやさいReport」**
野菜を食べた際のレポートを投稿できます。自炊したものだけではなく、コンビニやスーパーなどで購入したものでも投稿可能です。

**「おやさいReport」の閲覧**
他ユーザーの投稿を参考に、手軽な野菜摂取のアイデアを得ることができます。
レシピ付きの投稿ではAIのサポート機能により、家にある食材で実現できる代用レシピを提案してもらうことができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：25〜30時間 = 12〜15ストーリーポイント
- 11/4の週は予定があるため少なめに設定しております

■ProjectsのURL
[おやさいUP開発プロジェクト](https://github.com/users/erijawa/projects/2/views/1?sumFields=%5B140563786%5D&hideItemsCount=false)

■MVPリリースまで
- [ ] 環境構築
- [ ] Herokuデプロイ
- [ ] トップページ
- [ ] ヘッダー、フッター
- [ ]  ユーザー登録機能
- [ ]  ログイン機能
- [ ]  新規投稿機能
- [ ]  投稿一覧機能（未ログインでも閲覧可能）
- [ ]  投稿詳細閲覧機能（未ログインでも閲覧可能）
- [ ]  投稿編集機能
- [ ]  投稿削除機能
- [ ]  マイページ
- [ ]  野菜摂取カレンダーの表示
- [ ]  プロフィール編集機能
- [ ]  自分の投稿一覧
- [ ]  野菜摂取記録機能

■MVP後
- [ ]  検索機能(投稿内容、タグ、レシピの有無)
- [ ] オートコンプリート検索機能
- [ ] ブックマーク機能
- [ ] ユーザーのレベルアップ機能
- [ ] 投稿の下書き保存・編集機能
- [ ] AIによる代用品レシピ提案機能 
- [ ] SNSログイン（Google、LINEログイン）
- [ ] LINE通知
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] CI（GitHubActions）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] OGP

■MVPレビュー依頼予定日
予定日：2024年 12月 2日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- i18n
- CI（GitHubActions）
- マイページ
- プロフィール
- おやさいLog
- Cal-Heatmap

**Comment by erijawa** [comment]
ご確認＆ご提案いただきありがとうございます。
上記カードを本リリースに回せば、少しスケジュールに余裕が出そうです。
スケジュール見積もり面談でもご相談したいと思います。
